# Generated by Django 6.0.1 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_session_id',
            field=models.CharField(blank=True, help_text='GCash checkout session ID for payment tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_data',
            field=models.JSONField(blank=True, help_text='Raw webhook data from GCash payment gateway', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_received',
            field=models.BooleanField(default=False, help_text='Whether webhook confirmation has been received'),
        ),
    ]
