# Generated by Django 6.0.1 on 2026-03-16 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Settings', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='abnormal_threshold',
            field=models.FloatField(default=2.0, help_text='Standard deviations for abnormal detection (higher = less sensitive)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_generate_bills',
            field=models.BooleanField(default=True, help_text='Automatically generate bills at end of month'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 16, 23, 51, 41, 867669, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='electricity_rate',
            field=models.FloatField(default=23.0, help_text='PHP per kWh'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='late_penalty_amount',
            field=models.FloatField(default=50.0, help_text='PHP'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='reminder_days_before',
            field=models.IntegerField(default=3, help_text='Send reminder X days before due'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='Smart Energy Monitor', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
