# Generated by Django 6.0.1 on 2026-04-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_payment_checkout_session_id_payment_webhook_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='admin_email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='admin_name',
            field=models.CharField(default='System Administrator', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='admin_phone',
            field=models.CharField(default='+63 XXX XXX XXXX', max_length=20),
        ),
    ]
