# Generated by Django 6.0.1 on 2026-03-27 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_billing_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='days_occupied',
            field=models.IntegerField(default=0, help_text='Number of days tenant occupied the room this month'),
        ),
        migrations.CreateModel(
            name='TenantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='system.userprofile')),
            ],
            options={
                'ordering': ['-move_in_date'],
            },
        ),
        migrations.AddField(
            model_name='billing',
            name='tenant_assignment',
            field=models.ForeignKey(blank=True, help_text='Which tenant assignment this bill is for (for prorated bills)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.tenantassignment'),
        ),
    ]
