# Generated by Django 6.0.1 on 2026-04-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_systemsettings_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyusage',
            name='current',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='energyusage',
            name='power',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='energyusage',
            name='voltage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='kwh',
            field=models.FloatField(default=0),
        ),
    ]
