# Generated by Django 6.0.1 on 2026-03-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_billing_days_occupied_tenantassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='abnormal_threshold',
            field=models.FloatField(default=2.0, help_text='Standard deviations for abnormal detection'),
        ),
    ]
