# Generated by Django 6.0.1 on 2026-04-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_energyusage_current_energyusage_power_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='usage',
        ),
    ]
