# Generated by Django 6.0.1 on 2026-05-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_room_usage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('room', 'billing_month')},
        ),
    ]
