# Generated by Django 6.0.1 on 2026-03-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
