# Generated by Django 6.0.1 on 2026-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_billing_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='action_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='visibility',
            field=models.CharField(choices=[('both', 'Both Admin and Tenant'), ('admin_only', 'Admin Only'), ('tenant_only', 'Tenant Only')], default='both', max_length=20),
        ),
    ]
