# Generated by Codex on 2026-05-21

from django.db import migrations


def create_activitylog_table_if_missing(apps, schema_editor):
    ActivityLog = apps.get_model('system', 'ActivityLog')
    existing_tables = schema_editor.connection.introspection.table_names()

    if ActivityLog._meta.db_table not in existing_tables:
        schema_editor.create_model(ActivityLog)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alert_action_url_alert_visibility'),
    ]

    operations = [
        migrations.RunPython(create_activitylog_table_if_missing, migrations.RunPython.noop),
    ]
