# Generated by Django 6.0.1 on 2026-04-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_penalty_edit',
            field=models.BooleanField(default=False, help_text='Allow editing of late penalty amount'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_rate_edit',
            field=models.BooleanField(default=False, help_text='Allow editing of electricity rate'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_reminder_days_edit',
            field=models.BooleanField(default=False, help_text='Allow editing of reminder days'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_reminders',
            field=models.BooleanField(default=True, help_text='Enable/disable automatic email reminders'),
        ),
    ]
