# Generated by Django 6.0.1 on 2026-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_ensure_activitylog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='owner_announcement',
            field=models.TextField(blank=True, default='', help_text='Announcement shown on tenant dashboard'),
        ),
    ]
