# Generated by Django 6.0.1 on 2026-04-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_systemsettings_enable_penalty_edit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_penalty_edit',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_rate_edit',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_reminder_days_edit',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_reminders',
        ),
    ]
