# Generated by Django 6.0.1 on 2026-09-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_userprofile_agreed_to_privacy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-due_date', 'room__name']},
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='billing',
            name='cycle_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='billing',
            constraint=models.UniqueConstraint(fields=('room', 'tenant_assignment', 'cycle_start'), name='unique_billing_cycle_per_room'),
        ),
    ]
